site_name: OpenAleph
site_url: https://docs.openaleph.org
repo_url: https://github.com/investigativedata/aleph
nav:
  - index.md
theme:
  name: material
  logo: https://openaleph.org/assets/Logo/RGB/Open-Aleph-Logo-RGB-Square-Neg.svg
  favicon: https://dataresearchcenter.org/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - navigation.footer
    - toc.follow
    - content.code.copy
  custom_dir: docs/overrides
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: material/mail
      link: mailto:hi@dataresearchcenter.org
    - icon: material/web
      link: https://openaleph.org
    - icon: material/github
      link: https://github.com/investigativedata/aleph
    - icon: material/linkedin
      link: https://www.linkedin.com/company/dataresearchcenter/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  # - mkdocstrings:
  #     default_handler: python
  #     handlers:
  #       python:
  #         options:
  #           docstring_style: google
  #           show_root_heading: false
  #           show_object_full_path: false
